### ISSUE TITLE
Iserv never finishes

### ISSUE THREAD

**Issue by vmchale** [zw3rk/ghc-slave#1]
I don't know if this is due to client or server-side setup, but I figured I'd ask here to see if you have any insight. When I try to cross-compile as described in the guide on medium, the slave does this:

```bash
Opening socket
Listening on port 5000
Staring serv
iserv: MallocStrings ["KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","b","a","KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","b","a","Double","GHC.Types","ghc-prim","Double","GHC.Types","ghc-prim","KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","KahanSum"]
iserv: return: [RemotePtr 55412792,RemotePtr 55412808,RemotePtr 55412824,RemotePtr 55412864,RemotePtr 55412880,RemotePtr 55412896,RemotePtr 55412912,RemotePtr 55412928,RemotePtr 55412968,RemotePtr 55412984,RemotePtr 55413000,RemotePtr 55413016,RemotePtr 55413032,RemotePtr 55413048,RemotePtr 55413064,RemotePtr 55413080,RemotePtr 55413096,RemotePtr 55413112,RemotePtr 55413128,RemotePtr 55413168]
```

And then neither client nor server do anything else. 

Thanks for the project by the way!

**Comment by vmchale** [comment]
Here is the client-side output:

```bash
Trying to connect to 192.168.1.4:5000
Created socket for 192.168.1.4:5000
connected
Starting proxy
Msg:      ghc -- proxy -> slave: MallocStrings ["KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","b","a","KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","b","a","Double","GHC.Types","ghc-prim","Double","GHC.Types","ghc-prim","KahanSum","Numeric.Sum","math-functions-0.2.1.0-inplace","KahanSum"]
```

**Comment by angerman** [comment]
Sorry to hear that. How recent are your bootstrap compiler and the cross compiler? There is quite a bit of churn happening I'm afraid!

Best would be to build a ghc bootstrap compiler from the same sources as the cross compiler. That is:
building ghc from zw3rk/ghc/my-ghc, and then building the cross compiler from the same source. See the [zw3rk/ghc-build-scripts](https://github.com/zw3rk/ghc-build-scripts) repository. 

`PATH=$PREFIX:$PATH ./build-mobile-ghcs --prefix=$PREFIX --iconv=... --libffi=... "host aarch64-ios"`

should for example build the host compiler and the aarch64-ios compiler, with the just built host compiler.

The underlying issue might be that the template-haskell package is not recent enough.

**Comment by angerman** [comment]
I assume this was resolved? Feel free to reopen this issue if it still persists.
